apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: ingress-nginx
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-infra
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.14.0
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/do-loadbalancer-name: "lb-morichal-dev"
              service.beta.kubernetes.io/do-loadbalancer-type: "REGIONAL_NETWORK"
          publishService:
            enabled: true
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
          admissionWebhooks:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipHooks=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: ingress-nginx-admission
      jsonPointers:
        - /metadata/resourceVersion
    - group: batch
      kind: Job
      name: ingress-nginx-admission-create
    - group: batch
      kind: Job
      name: ingress-nginx-admission-patch

