apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-ingress
    environment: prod
spec:
  project: k8s-infra
  source:
    repoURL: https://github.com/Deploy-Staff/morichal-k8s-infra
    targetRevision: main
    path: operators/argocd
    directory:
      include: argocd-ingress-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

