apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-ingress
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-infra
  source:
    repoURL: https://github.com/dijarvrella/k8s-infra
    targetRevision: dev
    path: operators/argocd
    directory:
      include: argocd-ingress-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

